# Seeker File Browser - Docker Compose Configuration

services:
  seeker:
    image: ipradeepmishra/seeker:latest
    container_name: seeker
    restart: unless-stopped
    ports:
      - "7335:3000"
    volumes:
      # Configuration directory (required) - stores databases
      - ./config-test:/config
      # Change this to your actual data directory
      - /data:/data
      # Add more mounts as needed and mount them in settings page
      - /storage:/storage

    environment:
      - PORT=3000 # optional. default is 3000. update the port in the healthcheck if you changed it.
      - HOST=0.0.0.0 # optional. default is 0.0.0.0.
      - CONFIG_PATH=/config
      - DEFAULT_MOUNT=/data
    healthcheck:
      test: [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health" # update the port if you changed it in the environment variables.
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
