# docker-compose.build.yml
# For developers - builds image locally from source

services:
  seeker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seeker
    restart: unless-stopped
    ports:
      - "7335:3000"
    volumes:
      # Configuration directory (required) - stores databases
      - ./config:/config
      # Change this to your actual data directory
      - ./:/data
      # Add more mounts as needed and mount them in settings page
      - ./src:/storage

    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - CONFIG_PATH=/config
      - DEFAULT_MOUNT=/data
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
